In [1]:
!pip install git+https://github.com/hilolani/mif.git

  Cloning https://github.com/hilolani/mif.git to /tmp/pip-req-build-7iuorlgy
  Running command git clone --filter=blob:none --quiet https://github.com/hilolani/mif.git /tmp/pip-req-build-7iuorlgy
  Resolved https://github.com/hilolani/mif.git to commit d2b3275e505ef5bde94ca1fc843e3034983ed88a
  Preparing metadata (setup.py) ... done
  Created wheel for mif: filename=mif-0.1-py3-none-any.whl size=750729 sha256=c00929b8d9f371817a5f894010108828920f6e216fa198567808a7b581f82e21
  Stored in directory: /tmp/pip-ephem-wheel-cache-0_wtza0b/wheels/d6/4d/70/d10192d51a1e14d0bce7229bdb2cb84cc489121a8743e13e57
Successfully built mif


In [4]:
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
#This was done on Google Colab.

from mif import *
mif = load_mif()
print(mif)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
{'erdosReny': '/usr/local/lib/python3.12/dist-packages/mif/data/ErdosReny.mtx', 'gadget': '/usr/local/lib/python3.12/dist-packages/mif/data/gadget.mtx', 'heterophilly': '/usr/local/lib/python3.12/dist-packages/mif/data/heterophilly.mtx', 'homophilly': '/usr/local/lib/python3.12/dist-packages/mif/data/homophilly.mtx', 'karateclub': '/usr/local/lib/python3.12/dist-packages/mif/data/karateclub.mtx', 'scalefree': '/usr/local/lib/python3.12/dist-packages/mif/data/scalefree.mtx', 'eat': '/usr/local/lib/python3.12/dist-packages/mif/data/eat.mtx', 'DESCR': 'This is a toy dataset consisting of six sparse matrices in Matrix Market format.'}


In [5]:
mtxlist = [mif.gadget,mif.karateclub,mif.erdosReny,mif.scalefree,mif.homophilly,mif.heterophilly]
adjacencyinfocheckedlist = [adjacencyinfocheck(i) for i in mtxlist]
adjacencylist = ['gadget', 'karateclub', 'erdosReny', 'scalefree', 'homophilly', 'heterophilly']

log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoader] Loaded .mtx file → CSR.
2025-11-03 02:14:49 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(106, 106), nnz=986)
log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoader] Loaded .mtx file → CSR.
2025-11-03 02:14:49 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(34, 34), nnz=156)
log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoader] Loaded .mtx file → CSR.
2025-11-03 02:14:49 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(100, 100), nnz=7866)
log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoader] Loaded .mtx file → CSR.
2025-11-03 02:14:49 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(100, 100), nnz=971)
log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoader] Loaded .mtx file → CSR.
2025-11-03 02:14:49 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(100, 100), nnz=4203)
log name: MatrixLoader
2025-11-03 02:14:49 [MatrixLoade

In [ ]:
"""
Try
!cat /content/MiF.log
!cat /content/matrix.log
"""

In [6]:
#This was done on Google Colab.
def save_sparse_to_json(matrix, path):
    if not issparse(matrix):
        matrix = csr_matrix(matrix)
    coo = matrix.tocoo()
    data = {
        "row": coo.row.tolist(),
        "col": coo.col.tolist(),
        "data": coo.data.tolist(),
        "shape": list(coo.shape)
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f)
save_sparse_to_json(adjacencyinfocheckedlist[1],"/content/drive/My Drive/Colab Notebooks/karate.json")
karatejson = fileOnColab("karate.json")
adjacencyinfocheck(karatejson)

/content/drive/My Drive/Colab Notebooks/karate.json
log name: MatrixLoader
2025-11-03 02:14:56 [MatrixLoader] Loaded sparse JSON (COO format) → CSR.
2025-11-03 02:14:56 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(34, 34), nnz=156)


<SafeCSR shape=(34, 34), nnz=156, dtype=float64>

In [7]:
#This was done on Google Colab.
karatenpy =adjacencyinfocheckedlist[1].todense()
print(karatenpy)
print(type(karatenpy))
adjacencyinfocheck(np.array(karatenpy))

[[0 1 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 1 1]
 [0 0 1 ... 1 0 1]
 [0 0 0 ... 1 1 0]]
<class 'numpy.matrix'>
log name: MatrixLoader
2025-11-03 02:15:20 [MatrixLoader] Converting dense ndarray to CSR format (shape=(34, 34))
2025-11-03 02:15:20 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(34, 34), nnz=156)


<SafeCSR shape=(34, 34), nnz=156, dtype=int64>

In [18]:
#This was done on Google Colab.
with open('/content/drive/My Drive/Colab Notebooks/karate.pkl', 'wb') as f:
    pickle.dump(karatenpy, f)
karatepkl = fileOnColab("karate.pkl")
adjacencyinfocheck(karatepkl)

/content/drive/My Drive/Colab Notebooks/karate.pkl
log name: MatrixLoader
log name: MatrixLoader
2025-11-03 02:29:18 [MatrixLoader] Converting dense ndarray to CSR format (shape=(34, 34))
2025-11-03 02:29:18 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(34, 34), nnz=156)
2025-11-03 02:29:18 [MatrixLoader] Matrix loaded successfully (type=SafeCSR, shape=(34, 34), nnz=156)


<SafeCSR shape=(34, 34), nnz=156, dtype=int64>

In [17]:
#This was done on Google Colab.
np.savez("/content/drive/My Drive/Colab Notebooks/karate", karatenpy)
karatenpz = fileOnColab("karate.npz")
adjacencyinfocheck(karatenpz)

/content/drive/My Drive/Colab Notebooks/karate.npz
log name: MatrixLoader
2025-11-03 02:26:29 [MatrixLoader] Loaded dense .npz file → CSR.
2025-11-03 02:26:29 [MatrixLoader] Matrix loaded successfully (type=csr_matrix, shape=(34, 34), nnz=156)


<SafeCSR shape=(34, 34), nnz=156, dtype=int64>

The following is a showcase with Karate club.

In [10]:
MiF(adjacencyinfocheckedlist[1], 4, 32, 0.5, 3)

log name: MiF
log name: MiF
2025-11-03 02:17:34 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.


np.float64(0.00319517086847179)

In [12]:
MiF_broadcast(adjacencyinfocheckedlist[1], 3)

log name: MiF
log name: MiF
34
log name: MiF
log name: MiF
2025-11-03 02:17:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:17:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:17:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. w

[[3, 0, np.float64(0.10287618822169536)],
 [3, 1, np.float64(0.11246038170048131)],
 [3, 2, np.float64(0.105856363630985)],
 [3, 4, np.float64(0.016273004862745834)],
 [3, 5, np.float64(0.015451231517468984)],
 [3, 6, np.float64(0.015451231517468984)],
 [3, 7, np.float64(0.14523190300250574)],
 [3, 8, np.float64(0.01773891854249341)],
 [3, 9, np.float64(0.013058588488864924)],
 [3, 10, np.float64(0.016273004862745834)],
 [3, 11, np.float64(0.019577882669195107)],
 [3, 12, np.float64(0.20171698534104984)],
 [3, 13, np.float64(0.12757116941668883)],
 [3, 14, np.float64(0.0017972981920494257)],
 [3, 15, np.float64(0.0017972981920494257)],
 [3, 16, np.float64(0.0037360611450214516)],
 [3, 17, np.float64(0.026574969559341004)],
 [3, 18, np.float64(0.0017972981920494257)],
 [3, 19, np.float64(0.020393309131807678)],
 [3, 20, np.float64(0.0017972981920494257)],
 [3, 21, np.float64(0.026574969559341004)],
 [3, 22, np.float64(0.0017972981920494257)],
 [3, 23, np.float64(0.001925205592813683)],


In [13]:
MiF_broadcast(adjacencyinfocheckedlist[1], 3, loop = 1)

log name: MiF
log name: MiF
34
log name: MiF
log name: MiF
2025-11-03 02:18:24 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:18:24 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:18:24 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. w

[[3, 0, np.float64(0.10287618822169536)],
 [3, 1, np.float64(0.11246038170048131)],
 [3, 2, np.float64(0.105856363630985)],
 [3, 3, np.float64(0.016273004862745834)],
 [3, 4, np.float64(0.015451231517468984)],
 [3, 5, np.float64(0.015451231517468984)],
 [3, 6, np.float64(0.14523190300250574)],
 [3, 7, np.float64(0.01773891854249341)],
 [3, 8, np.float64(0.013058588488864924)],
 [3, 9, np.float64(0.016273004862745834)],
 [3, 10, np.float64(0.019577882669195107)],
 [3, 11, np.float64(0.20171698534104984)],
 [3, 12, np.float64(0.12757116941668883)],
 [3, 13, np.float64(0.0017972981920494257)],
 [3, 14, np.float64(0.0017972981920494257)],
 [3, 15, np.float64(0.0037360611450214516)],
 [3, 16, np.float64(0.026574969559341004)],
 [3, 17, np.float64(0.0017972981920494257)],
 [3, 18, np.float64(0.020393309131807678)],
 [3, 19, np.float64(0.0017972981920494257)],
 [3, 20, np.float64(0.026574969559341004)],
 [3, 21, np.float64(0.0017972981920494257)],
 [3, 22, np.float64(0.001925205592813683)],
 

In [14]:
MiFDI(adjacencyinfocheckedlist[1], loop = 1)

log name: MiF
log name: MiF
2025-11-03 02:18:55 [MiF] the smallest degree: 1
2025-11-03 02:18:55 [MiF] the node numbers with the smallest degree : [11]

log name: MiF
log name: MiF
2025-11-03 02:18:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:18:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:18:55 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counte

In [16]:
MiFDI(adjacencyinfocheckedlist[1], startingvertices="max")

log name: MiF
log name: MiF
2025-11-03 02:19:34 [MiF] the smallest degree: 1
2025-11-03 02:19:34 [MiF] the node numbers with the smallest degree : [11]

log name: MiF
log name: MiF
2025-11-03 02:19:34 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:19:34 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counted starting from 0.In other words, it is assumed that a sparse matrix with a 0-based index created in C, C++, Python,etc. was input here.
log name: MiF
log name: MiF
2025-11-03 02:19:34 [MiF] Here, all integer values are assumed to be 0-based indexes, i.e. data and parameters --including node numbers and gamma-- that are counte

([[0, np.float64(-0.2076393647782445)],
  [1, np.float64(-3.884047951519476)],
  [2, np.float64(-3.8993154236502643)],
  [3, np.float64(-3.8747743147341467)],
  [4, np.float64(-3.7978132735980186)],
  [5, np.float64(-3.809735918554925)],
  [6, np.float64(-3.809735918554925)],
  [7, np.float64(-3.865065500607186)],
  [8, np.float64(-3.8925586411873847)],
  [9, np.float64(-6.161680931542804)],
  [10, np.float64(-3.7978132735980186)],
  [11, 0],
  [12, np.float64(-3.791101839010032)],
  [13, np.float64(-3.8914645491745254)],
  [14, np.float64(-7.1807237074616985)],
  [15, np.float64(-7.1807237074616985)],
  [16, np.float64(-5.295842452605739)],
  [17, np.float64(-3.809735918554925)],
  [18, np.float64(-7.1807237074616985)],
  [19, np.float64(-3.8671841454674714)],
  [20, np.float64(-7.1807237074616985)],
  [21, np.float64(-3.809735918554925)],
  [22, np.float64(-7.1807237074616985)],
  [23, np.float64(-6.963401667614471)],
  [24, np.float64(-6.130539725463252)],
  [25, np.float64(-6.13591